version: '3.9'
services:
  
  scraping-data-app:
    build:
      context : .
      dockerfile: Dockerfile
    image: scraping-data
    container_name: scraping-data-app
    command: sleep infinity
    volumes:
      - ../:/code/dev
      - ~/.gitconfig:/home/scraping/.gitconfig
    user: dev
    # TODO: Discover how to work with profiles. Currently, it is uncommented,
    # vscode is not able to launch the the devcontainer.
    # profiles:
    #   - dev
