name: Deploy Containers
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    #  branches:
    #    - main

env:
  DOCKER_COMPOSE_FILE: .devcontainer/compose.yml
  REQUIREMENTS: .devcontainer/requirements.txt

jobs:
  Unit-Testig-Container:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: Set up Docker Compose
      run: |
        docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d

    - name: Wait for containers to start
      run: |
        docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} ps

    - name: Run all tests
      run: |
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T scraping-data-app python3 /code/dev/tests/main.py
    
    - name: Copy reports from DevContainer to Host
      run: docker cp scraping-data-app:/tmp/reports ${{ github.workspace }}
  
    - name: Upload reports as artifact
      uses: actions/upload-artifact@v3
      with:
          name: test-reports
          path: ${{ github.workspace }}/reports

          